[package]
name = "loopback"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
dotenvy = "0.15.7"
pnet = "0.35.0"
tokio = { version = "1.42.0", features = ["full"] }
warp = "0.3.7"
